# Generated by Django 4.2.3 on 2023-07-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='current_bolts_state_for_front',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=3, null=True)),
                ('path_cam1', models.CharField(blank=True, max_length=512, null=True)),
                ('path_cam2', models.CharField(blank=True, max_length=512, null=True)),
                ('state_cam1', models.CharField(blank=True, max_length=100, null=True)),
                ('state_cam2', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'app_current_bolts_state_for_front',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='current_seal_state_for_front',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=3, null=True)),
                ('path_cam1_left', models.CharField(blank=True, max_length=512, null=True)),
                ('path_cam1_right', models.CharField(blank=True, max_length=512, null=True)),
                ('path_cam2_left', models.CharField(blank=True, max_length=512, null=True)),
                ('path_cam2_right', models.CharField(blank=True, max_length=512, null=True)),
                ('state_cam1_left', models.CharField(blank=True, max_length=100, null=True)),
                ('state_cam1_right', models.CharField(blank=True, max_length=100, null=True)),
                ('state_cam2_left', models.CharField(blank=True, max_length=100, null=True)),
                ('state_cam2_right', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'app_current_seal_state_for_front',
                'managed': False,
            },
        ),
    ]
