# Generated by Django 4.2.3 on 2023-07-07 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replaced_carts_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_no', models.IntegerField(db_column='no', help_text='The number of the replaced (previous) cart.')),
                ('prev_cart_detected', models.DateTimeField(db_column='time', help_text='Time when replaced (previous) cart was last detected.')),
                ('new_no', models.IntegerField(db_column='replace_no', help_text='The number of the replacing (new) cart.')),
                ('created', models.DateTimeField(help_text='Record creation time.')),
            ],
            options={
                'db_table': 'app_replacedcarts',
                'managed': False,
            },
        ),
    ]
