# Generated by Django 4.2.3 on 2023-07-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replaced_carts_report', '0002_add_cartreplacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartReplacementReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_no', models.IntegerField(help_text='The number of the replaced (previous) cart. Duplicates CartReplacement model `prev_no`.')),
                ('new_no', models.IntegerField(help_text='The number of the replacing (new) cart. Duplicates CartReplacement model `new_no`.')),
                ('bad_bolt_cam1', models.ForeignKey(help_text='Bad bolt state record by cam1 observation. Null if cam1 state is good.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cam1_cart_replacement_reasons', to='replaced_carts_report.current_bolts_state_for_front')),
                ('bad_bolt_cam2', models.ForeignKey(help_text='Bad bolt state record by cam2 observation. Null if cam2 state is good.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cam2_cart_replacement_reasons', to='replaced_carts_report.current_bolts_state_for_front')),
                ('bad_seal_cam1_left', models.ForeignKey(help_text='Bad seal state record by left cam1 observation. Null if left cam1 state is good.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cam1_left_cart_replacement_reasons', to='replaced_carts_report.current_seal_state_for_front')),
                ('bad_seal_cam1_right', models.ForeignKey(help_text='Bad seal state record by right cam1 observation. Null if right cam1 state is good.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cam1_right_cart_replacement_reasons', to='replaced_carts_report.current_seal_state_for_front')),
                ('bad_seal_cam2_left', models.ForeignKey(help_text='Bad seal state record by left cam2 observation. Null if left cam2 state is good.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cam2_left_cart_replacement_reasons', to='replaced_carts_report.current_seal_state_for_front')),
                ('bad_seal_cam2_right', models.ForeignKey(help_text='Bad seal state record by right cam2 observation. Null if right cam2 state is good.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cam2_right_cart_replacement_reasons', to='replaced_carts_report.current_seal_state_for_front')),
                ('replacement', models.OneToOneField(help_text='Cart replacement record.', on_delete=django.db.models.deletion.CASCADE, related_name='cart_replacement_reason', to='replaced_carts_report.cartreplacement')),
            ],
        ),
    ]
